# Generated by Django 5.1.4 on 2026-08-11 06:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0003_submission_error_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractionTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("extractor_name", models.CharField(blank=True, default="", max_length=50)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("char_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extraction_tasks",
                        to="submissions.submissionasset",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_tasks",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "db_table": "extraction_extractiontask",
                "indexes": [
                    models.Index(
                        fields=["submission", "created_at"], name="extract_sub_created_idx"
                    ),
                    models.Index(fields=["submission", "status"], name="extract_sub_status_idx"),
                ],
            },
        ),
    ]
