# Generated by Django 5.1.4 on 2026-08-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extraction", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extractiontask",
            old_name="extractor_name",
            new_name="processor_name",
        ),
    ]
