# Generated by Django 5.1.4 on 2026-08-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extraction", "0002_rename_extractor_name_extractiontask_processor_name"),
        ("submissions", "0003_submission_error_message"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="extractiontask",
            index=models.Index(fields=["status", "updated_at"], name="extract_status_updated_idx"),
        ),
    ]
