# Generated by Django 5.1.4 on 2026-08-16 05:08

import apps.sharing.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("roasts", "0003_roastrun_owner_roastrun_roast_owner_created_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(
                        default=apps.sharing.models.generate_share_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="roasts.roastrun",
                    ),
                ),
            ],
            options={
                "db_table": "sharing_sharelink",
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("fire", "Brutal"),
                            ("skull", "Deceased"),
                            ("laughing", "Painfully funny"),
                            ("clap", "Fair"),
                        ],
                        max_length=20,
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "share_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="sharing.sharelink",
                    ),
                ),
            ],
            options={
                "db_table": "sharing_reaction",
            },
        ),
        migrations.AddIndex(
            model_name="sharelink",
            index=models.Index(fields=["roast", "created_at"], name="sharelink_roast_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="sharelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("roast",),
                name="unique_active_share_link_per_roast",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=("share_link", "reaction_type"), name="unique_reaction_type_per_share_link"
            ),
        ),
    ]
