# Generated by Django 5.1.4 on 2026-08-10 17:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0002_add_status_visibility_title_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoastRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('hinglish', 'Hinglish')], max_length=20)),
                ('intensity', models.CharField(choices=[('gentle', 'Gentle'), ('sarcastic', 'Sarcastic'), ('brutal', 'Brutal'), ('nuclear', 'Nuclear')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('engine_version', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roast_runs', to='submissions.submission')),
            ],
            options={
                'db_table': 'roasts_roastrun',
            },
        ),
        migrations.CreateModel(
            name='RoastFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('roast_text', models.TextField()),
                ('actual_feedback', models.TextField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('roast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='roasts.roastrun')),
            ],
            options={
                'db_table': 'roasts_roastfinding',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='RoastSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('roast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='roasts.roastrun')),
            ],
            options={
                'db_table': 'roasts_roastsection',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='roastrun',
            index=models.Index(fields=['submission', 'created_at'], name='roast_sub_created_idx'),
        ),
        migrations.AddIndex(
            model_name='roastrun',
            index=models.Index(fields=['submission', 'status'], name='roast_sub_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='roastrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'processing'])), fields=('submission', 'language', 'intensity'), name='unique_inflight_roast_per_submission_lang_intensity'),
        ),
        migrations.AddIndex(
            model_name='roastfinding',
            index=models.Index(fields=['roast', 'position'], name='finding_roast_position_idx'),
        ),
        migrations.AddIndex(
            model_name='roastfinding',
            index=models.Index(fields=['roast', 'severity'], name='finding_roast_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='roastsection',
            index=models.Index(fields=['roast', 'position'], name='section_roast_position_idx'),
        ),
        migrations.AddConstraint(
            model_name='roastsection',
            constraint=models.UniqueConstraint(fields=('roast', 'key'), name='unique_section_key_per_roast'),
        ),
    ]
