# Generated by Django 5.1.4 on 2026-08-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roasts', '0001_initial'),
        ('submissions', '0002_add_status_visibility_title_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='roastrun',
            name='final_verdict',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='roastrun',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roastrun',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='roastrun',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', 100)), _connector='OR'), name='roastrun_score_within_range'),
        ),
    ]
