# Generated by Django 5.1.4 on 2026-08-11 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roasts", "0002_add_summary_verdict_score"),
        ("submissions", "0003_submission_error_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="roastrun",
            name="owner",
            field=models.ForeignKey(
                default="00000000-0000-0000-0000-000000000000",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roast_runs",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="roastrun",
            index=models.Index(fields=["owner", "created_at"], name="roast_owner_created_idx"),
        ),
        migrations.AddIndex(
            model_name="roastrun",
            index=models.Index(fields=["status", "updated_at"], name="roast_status_updated_idx"),
        ),
    ]
