import type { Metadata } from "next"

import { GadbadBanner } from "@/components/marketing/gadbad-banner"
import { Container } from "@/components/shared/container"

export const metadata: Metadata = {
  title: "Terms of Service — Roast Anything",
  description:
    "The rules for using Roast Anything, written by a lawyer who also thought the jokes were funny.",
}

const SECTIONS = [
  {
    heading: "1. Welcome",
    body: [
      "By using Roast Anything (\"the Service\"), you agree to these Terms. If you don't agree, the only roast you'll be getting is this one: please don't use the Service.",
    ],
  },
  {
    heading: "2. What this actually is",
    body: [
      "Roast Anything takes something you submit — a resume, a website, or a GitHub profile — and uses AI to generate brutally honest, occasionally exaggerated feedback for entertainment and self-improvement purposes.",
      "It is not career counseling, legal advice, financial advice, a hiring decision, a code review from a senior engineer, or therapy. Treat every roast as one opinionated take generated by a language model, not gospel. Please don't rewrite your resume, quit your job, or delete your GitHub based solely on a joke a robot made about your commit history.",
    ],
  },
  {
    heading: "3. Accounts",
    body: [
      "You need an account to generate roasts. You must provide a valid email address and verify it via the one-time code we send you. You're responsible for keeping your login credentials secure and for anything that happens under your account.",
      "You must be at least 13 years old (or the minimum age of digital consent in your jurisdiction) to use the Service.",
    ],
  },
  {
    heading: "4. Your content",
    body: [
      "You keep ownership of whatever you submit — your resume, your website, your GitHub profile, your dignity. By submitting it, you give us a limited license to process it (including sending it to OpenAI) solely to generate your roast and operate the Service.",
      "If you choose to make a roast public — via a shareable roast card or the Wall of Fame — you're granting us a license to display that specific roast publicly until you remove it.",
      "You confirm you have the right to submit whatever you upload, and that it doesn't contain anyone else's private or sensitive information without their consent, or anything you don't have permission to share (e.g., a resume that isn't yours, someone else's private repo contents, etc.).",
    ],
  },
  {
    heading: "5. Third-party AI provider",
    body: [
      "Roasts are generated using OpenAI's models. Submitting content to Roast Anything means that content is sent to OpenAI for processing, subject to OpenAI's own terms and privacy policy. We don't control OpenAI's infrastructure or guarantee its outputs.",
    ],
  },
  {
    heading: "6. Roast quota & referrals",
    body: [
      "Roasts are rate-limited on a weekly quota per account, shown in your dashboard. Referral bonuses grant temporary extra quota and may be changed, capped, or revoked at our discretion, including for suspected abuse (fake referrals, self-referral loops, etc.).",
    ],
  },
  {
    heading: "7. Acceptable use",
    body: [
      "Don't use Roast Anything to: submit content that's illegal, infringing, harassing, or someone else's private information without consent; try to break, overload, or reverse-engineer the Service; abuse the referral or quota system; or use generated roasts to harass, defame, or bully a real person outside the spirit of \"friendly, opt-in roasting.\"",
      "We can suspend or terminate accounts that violate this section, no warning roast included.",
    ],
  },
  {
    heading: "8. AI-generated content disclaimer",
    body: [
      "Roasts are generated by AI models and may be inaccurate, incomplete, unfair, weirdly specific, or just not that funny. We don't guarantee the accuracy, quality, or appropriateness of any roast, and we're not liable for decisions you make based on one.",
      "If a roast output is offensive in a way that crosses from \"funny mean\" to something that shouldn't have been generated, please report it — we take that seriously even if the product's whole premise is voluntary insults.",
    ],
  },
  {
    heading: "9. Public content & the Wall of Fame",
    body: [
      "Featuring a roast on the Wall of Fame or generating a shareable card is opt-in and reversible from your dashboard. Once shared, we can't retroactively un-share copies others have already saved, screenshotted, or linked elsewhere.",
    ],
  },
  {
    heading: "10. Termination",
    body: [
      "You can delete your account at any time. We may suspend or terminate accounts that violate these Terms, pose a security risk, or are inactive for an extended period, in each case with notice where reasonably practicable.",
    ],
  },
  {
    heading: "11. Disclaimers & limitation of liability",
    body: [
      "The Service is provided \"as is,\" without warranties of any kind, express or implied. To the maximum extent permitted by law, Roast Anything and its team aren't liable for indirect, incidental, or consequential damages arising from your use of the Service, including any emotional damage caused by an unreasonably accurate roast.",
    ],
  },
  {
    heading: "12. Changes to these terms",
    body: [
      "We may update these Terms from time to time. If changes are material, we'll do our best to notify you (e.g., via email or an in-app notice) before they take effect. Continued use after that point means you accept the updated Terms.",
    ],
  },
  {
    heading: "13. Governing law",
    body: [
      "These Terms are governed by the laws of India, without regard to conflict-of-law principles. The courts of Pune, Maharashtra shall have exclusive jurisdiction over any disputes arising from these Terms or your use of the Service.",
    ],
  },
  {
    heading: "14. Contact",
    body: [
      "Questions about these Terms? Email hello@roastanything.com — we promise a straight answer, no jokes at your expense this time.",
    ],
  },
] as const

export default function TermsPage() {
  return (
    <Container className="max-w-3xl py-16 sm:py-20">
      <div className="space-y-2 text-center sm:text-left">
        <h1 className="font-display text-3xl font-medium text-foreground sm:text-4xl">
          Terms of Service
        </h1>
        <p className="font-mono text-xs tracking-widest text-muted-foreground uppercase">
          Last updated August 21, 2026
        </p>
      </div>

      <div className="mt-8">
        <GadbadBanner />
      </div>

      <div className="mt-2 space-y-10">
        {SECTIONS.map((section) => (
          <section key={section.heading} className="space-y-3">
            <h2 className="font-display text-lg font-medium text-foreground">
              {section.heading}
            </h2>
            {section.body.map((paragraph, i) => (
              <p key={i} className="text-sm leading-relaxed text-foreground/80">
                {paragraph}
              </p>
            ))}
          </section>
        ))}
      </div>
    </Container>
  )
}
