# Generated by Django 5.1.4 on 2026-08-10 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roasts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('hinglish', 'Hinglish')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('system_prompt', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ai_promptversion',
                'indexes': [models.Index(fields=['name', 'language', 'is_active'], name='prompt_name_lang_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'language', 'version'), name='unique_prompt_name_lang_version'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name', 'language'), name='unique_active_prompt_per_name_language')],
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('roast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to='roasts.roastrun')),
                ('prompt_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_requests', to='ai.promptversion')),
            ],
            options={
                'db_table': 'ai_airequest',
                'indexes': [models.Index(fields=['roast', 'created_at'], name='airequest_roast_created_idx')],
            },
        ),
    ]
