# Generated by Django 5.1.4 on 2026-08-10 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('submission_type', models.CharField(choices=[('resume', 'Resume'), ('website', 'Website'), ('github', 'GitHub Profile')], max_length=20)),
                ('source_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('is_private', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions_submission',
            },
        ),
        migrations.CreateModel(
            name='SubmissionAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=127)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='submissions.submission')),
            ],
            options={
                'db_table': 'submissions_submissionasset',
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['owner', 'created_at'], name='sub_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['owner', 'submission_type'], name='sub_owner_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('submission_type__in', ['website', 'github']), _negated=True), ('source_url__isnull', False), _connector='OR'), name='source_url_required_for_url_types'),
        ),
        migrations.AddIndex(
            model_name='submissionasset',
            index=models.Index(fields=['submission'], name='asset_submission_idx'),
        ),
    ]
