# Generated by Django 5.1.4 on 2026-08-10 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='label',
        ),
        migrations.AddField(
            model_name='submission',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='submission',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('link', 'Link'), ('public', 'Public')], default='private', max_length=20),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['owner', 'status'], name='sub_owner_status_idx'),
        ),
    ]
