# Generated by Django 5.1.4 on 2026-08-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_add_status_visibility_title_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
